import { CalendarDays, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { SiteShell } from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

type Kind = "all" | "destinations" | "experiences" | "sections";
export default function PublishedExplorer() {
  const { data, isLoading } = trpc.publishedContent.list.useQuery();
  const [query, setQuery] = useState(""); const [kind, setKind] = useState<Kind>("all"); const [region, setRegion] = useState("all"); const [recent, setRecent] = useState(false);
  const items = useMemo(() => { const rows = [ ...(data?.destinations ?? []).map((item) => ({ kind: "destinations" as const, slug: item.slug, title: item.title, description: item.description, imageUrl: item.imageUrl, region: item.region, meta: `${item.city} · ${item.region}`, updatedAt: item.updatedAt })), ...(data?.experiences ?? []).map((item) => ({ kind: "experiences" as const, slug: item.slug, title: item.title, description: item.description, imageUrl: item.imageUrl, region: item.region, meta: `${item.region}${item.season ? ` · ${item.season}` : ""}`, updatedAt: item.updatedAt })), ...(data?.sections ?? []).map((item) => ({ kind: "sections" as const, slug: item.slug, title: item.title, description: item.summary, imageUrl: item.imageUrl, region: item.sectionType === "festival" ? "مهرجان" : "قسم", meta: item.sectionType === "festival" ? "مهرجان" : "قسم منشور", updatedAt: item.updatedAt })) ]; const needle = query.trim().toLocaleLowerCase("ar"); const since = Date.now() - 30 * 24 * 60 * 60 * 1000; return rows.filter((item) => (kind === "all" || item.kind === kind) && (region === "all" || item.region === region) && (!recent || new Date(item.updatedAt).getTime() >= since) && (!needle || `${item.title} ${item.description} ${item.meta}`.toLocaleLowerCase("ar").includes(needle))); }, [data, kind, query, recent, region]);
  const regions = ["all", ...Array.from(new Set(items.length ? items.map((item) => item.region) : [ ...(data?.destinations ?? []).map((item) => item.region), ...(data?.experiences ?? []).map((item) => item.region), ...(data?.sections ?? []).map((item) => item.sectionType === "festival" ? "مهرجان" : "قسم") ]))];
  return <SiteShell><section className="discover-hero"><div className="page-frame"><p className="eyebrow light"><SlidersHorizontal size={14} /> فهرس حيّ</p><h1>استكشف ما نُشر حديثًا.</h1><p>ابحث وفِلتر الوجهات والتجارب والمهرجانات التي اعتمدتها إدارة المنصة.</p></div></section><section className="page-frame discover-controls"><label className="search-field"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث باسم مكان أو تجربة أو مهرجان…" /></label><div className="category-chips"><span className="filter-label">النوع</span>{(["all", "destinations", "experiences", "sections"] as Kind[]).map((item) => <button key={item} type="button" className={kind === item ? "is-active" : ""} onClick={() => setKind(item)}>{{ all: "الكل", destinations: "وجهات", experiences: "تجارب", sections: "مهرجانات وأقسام" }[item]}</button>)}</div><div className="category-chips"><span className="filter-label">المنطقة / النوع</span>{regions.map((item) => <button key={item} type="button" className={region === item ? "is-active" : ""} onClick={() => setRegion(item)}>{item === "all" ? "الكل" : item}</button>)}</div><label className="discover-recent"><input type="checkbox" checked={recent} onChange={(event) => setRecent(event.target.checked)} /> عرض المنشور خلال 30 يومًا</label></section><section className="page-frame discover-results"><p>تظهر <strong>{items.length}</strong> عناصر منشورة.</p>{isLoading && <span>جارٍ تحديث الفهرس…</span>}<div className="published-content-grid">{items.map((item) => <article key={`${item.kind}-${item.slug}`}>{item.imageUrl && <img src={item.imageUrl} alt={item.title} loading="lazy" />}<div><p><MapPin size={13} /> {item.meta}</p><h2>{item.title}</h2><span>{item.description}</span><Link href={`/published/${item.kind}/${item.slug}`}>افتح التفاصيل <CalendarDays size={14} /></Link></div></article>)}</div>{!isLoading && !items.length && <div className="empty-state"><h2>لا توجد عناصر منشورة تطابق هذا البحث.</h2><button className="button button-ink" type="button" onClick={() => { setQuery(""); setKind("all"); setRegion("all"); setRecent(false); }}>إعادة الضبط</button></div>}</section></SiteShell>;
}
