import { CheckCircle2, LockKeyhole, Send, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { SiteShell } from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

export default function VisaIntake() {
  const [form, setForm] = useState({ fullName: "", email: "", nationality: "", residenceCountry: "", travelPurpose: "", intendedArrival: "", notes: "", consent: false });
  const submit = trpc.visa.submitIntake.useMutation();
  const send = (event: FormEvent) => { event.preventDefault(); if (!form.consent) return; submit.mutate({ ...form, consent: true, intendedArrival: form.intendedArrival || null, notes: form.notes || null }); };
  const field = (label: string, key: keyof typeof form, type = "text") => <label className="visa-field"><span>{label}</span><input type={type} value={typeof form[key] === "string" ? form[key] as string : ""} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required /></label>;
  return <SiteShell><section className="visa-intake-hero"><div className="page-frame"><p className="eyebrow light"><ShieldCheck size={14} /> طلب أولي منظم</p><h1>ابدأ طلبك، ثم انتظر الإحالة الرسمية.</h1><p>هذا النموذج ليس قرارًا أو تأشيرة إلكترونية، ولا يتصل بجهة حكومية حاليًا. يُحفظ الطلب بأمان للمراجعة الداخلية حتى اعتماد قناة الإحالة الرسمية.</p></div></section><section className="page-frame visa-intake-layout"><aside><LockKeyhole size={26} /><h2>خصوصية ومسؤولية</h2><p>لا تدخل رقم جواز السفر أو صور الوثائق أو بيانات الدفع في هذه المرحلة. تستخدم المعلومات الأساسية فقط لإنشاء سجل أولي قابل للمراجعة.</p><a href="https://evisa.gov.ly/" target="_blank" rel="noreferrer">بوابة التأشيرة الرسمية</a></aside>{submit.data ? <div className="visa-success"><CheckCircle2 size={30} /><h2>تم استلام الطلب الأولي.</h2><p>رقمك المرجعي: <strong>{submit.data.referenceCode}</strong></p><p>الحالة الحالية: قيد المراجعة الداخلية. لن تتم إحالة الطلب خارج المنصة حتى اعتماد قناة رسمية.</p></div> : <form onSubmit={send}>{field("الاسم الكامل", "fullName")}{field("البريد الإلكتروني", "email", "email")}<div className="visa-pair">{field("الجنسية", "nationality")}{field("بلد الإقامة", "residenceCountry")}</div>{field("غرض الزيارة", "travelPurpose")}<label className="visa-field"><span>موعد الوصول المتوقع (اختياري)</span><input type="date" value={form.intendedArrival} onChange={(event) => setForm({ ...form, intendedArrival: event.target.value })} /></label><label className="visa-field"><span>ملاحظات (اختيارية)</span><textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label><label className="visa-consent"><input type="checkbox" checked={form.consent} onChange={(event) => setForm({ ...form, consent: event.target.checked })} required /> أوافق على حفظ هذه البيانات الأساسية لمراجعة الطلب الأولي فقط.</label><button className="button button-ink" disabled={submit.isPending || !form.consent}><Send size={16} /> إرسال الطلب الأولي</button>{submit.isError && <p className="visa-error">تعذر حفظ الطلب الآن. راجع الحقول وحاول مرة أخرى.</p>}</form>}</section></SiteShell>;
}
